name: "Set up repository for CI"
description: "Install development dependencies"

inputs:
    python-version:
        description: "Python version to install"
        default: "3.12"

runs:
    using: "composite"
    steps:
        - name: "Set up Python"
          id: setup-python
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.python-version }}
              update-environment: false

        - name: Install uv
          uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6

        - name: Install poe
          shell: bash
          run: |
              uv tool install poethepoet

        - name: "Install development dependencies"
          shell: bash
          env:
              python_path: ${{ steps.setup-python.outputs.python-path }}
          run: |
              uv sync --all-groups --python "$python_path"
