name: "Set up repository for CI"
description: "Install development dependencies"

inputs:
    python-version:
        description: "Python version to install"
        default: "3.11"
    poetry-version:
        description: "Poetry version to install"
        default: "1.3.2"
    pip-cache:
        description: "Pip cache directory"
        default: "${{ github.workspace }}/.cache/pip"
    poetry-cache:
        description: "Poetry cache directory"
        default: "${{ github.workspace }}/.cache/pypoetry"

runs:
    using: "composite"
    steps:
        - name: "Set up Python"
          id: setup-python
          uses: actions/setup-python@v4
          with:
              python-version: ${{ inputs.python-version }}

        - name: "Set up dependency cache"
          uses: actions/cache@v3
          with:
              key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ inputs.poetry-version }}-${{ hashFiles('poetry.lock') }}
              path: |
                  ${{ inputs.pip-cache }}
                  ${{ inputs.poetry-cache }}

        - name: "Install poetry"
          shell: bash
          run: |
              pip config set global.cache-dir ${{ inputs.pip-cache }}
              pip install "poetry==${{ inputs.poetry-version }}"

        - name: "Install development dependencies"
          shell: bash
          run: |
              poetry config cache-dir ${{ inputs.poetry-cache }}
              poetry install --sync
