name: "Set up repository for CI"
description: "Install development dependencies"

inputs:
    python-version:
        description: "Python version to install"
        default: "3.11"
    poetry-version:
        description: "Poetry version to install"
        default: "1.3.2"
    cache:
        description: "Cache directory"
        default: ".cache"
    shell:
        description: "Shell"
        default: ${{ runner.os != 'windows' && 'bash' || 'pwsh'}}

runs:
    using: "composite"
    steps:
        - name: "Set up Python"
          id: setup-python
          uses: actions/setup-python@v4
          with:
              python-version: ${{ inputs.python-version }}

        - name: "Set up dependency cache"
          uses: actions/cache@v3
          with:
              key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ inputs.poetry-version }}-${{ hashFiles('poetry.lock') }}
              path: ${{ inputs.cache }}

        - name: "Set up PATH"
          shell: ${{ inputs.shell }}
          run: echo "${{ inputs.cache }}/tools/bin" >> $GITHUB_PATH

        - name: "Install poetry"
          shell: ${{ inputs.shell }}
          run: poetry --version || pip install "poetry==${{ inputs.poetry-version }}"

        - name: "Install development dependencies"
          shell: ${{ inputs.shell }}
          run: |
              poetry config cache-dir "${{ inputs.cache }}/poetry"
              poetry install --sync
